context:
  name: certbot-dns-google
  version: "5.2.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: dcbcdb2334d04988520470484e4fc5602f11d0aaa84c983c6de10e41b73dc20a

build:
  noarch: python
  script: python -m pip install . -vv
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - acme >=${{ version }}
    - certbot >=${{ version }}
    - google-api-python-client >=1.6.5
    - google-auth >=2.16.0

tests:
  - python:
      imports:
        - certbot_dns_google
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://certbot.eff.org
  summary: Google Cloud DNS Authenticator plugin for Certbot
  license: Apache-2.0
  license_file: LICENSE.txt
  documentation: https://certbot.eff.org
  repository: https://github.com/certbot/certbot

extra:
  recipe-maintainers:
    - pavelzw
